### ISSUE TITLE
Publish to Central

### ISSUE THREAD

**Issue by tduchateau** [keub/remote-resources-maven-plugin#1]
This awesome plugin should be available in Maven Central!

**Comment by tonywrzos** [comment]
This fantastic plugin is available on Maven Central.
Just add this plugin in build section on your pom.xml : 

```
  <groupId>com.github.keub</groupId>
  <artifactId>remote-resources-maven-plugin</artifactId>
  <version>1.0</version>
```

And configure remote resources to copy into ur project.
http://keub.github.io/remote-resources-maven-plugin/usage.html

**Comment by tduchateau** [comment]
Nice :-)
